(TeX-add-style-hook
 "ComponentDataBlocks"
 (lambda ()
   (LaTeX-add-labels
    "sec:COMPdataBlockManagementDesign"
    "sec:BasicConceptforReading"
    "fig:III_ForwardReading"
    "sec:ReadingSteps"
    "sec:ContainerContextInformation"
    "sec:SizeDetermination"
    "sec:CountDetermination"
    "sec:FieldParsing"
    "sec:TerminatedFields"
    "sec:LazyFields"
    "sec:BackwardReading"
    "sec:BasicConceptforWriting"
    "sec:StatesofDatablocks"
    "tab:Datablockstates"
    "fig:III_DBStates.pdf"
    "sec:WritingActions"
    "sec:CreatingNewDatablocks"
    "sec:InsertingDatablocks"
    "tab:InsertProCon"
    "sec:RemovingDatablocks"
    "sec:ModifyingDatablocks"
    "sec:Flushing"
    "sec:UndoallChanges"
    "sec:APIDesign"))
 :latex)

