language: java
before_install: cd jMeta
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11
  - oraclejdk12
  - oraclejdk13
  - oraclejdk14
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14