//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.19 at 10:39:24 AM CEST 
//


package de.je.jmeta.extmanager.impl.jaxb.extpoints;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExtensionPointsConfigurationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtensionPointsConfigurationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="ExtensionBundleSearchPath" type="{www.easytag.de/XMLSchema_v1_0}ExtensionBundleSearchPathType"/>
 *         &lt;element name="ExtensionPoints" type="{www.easytag.de/XMLSchema_v1_0}ExtensionPointsType"/>
 *       &lt;/all>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtensionPointsConfigurationType", namespace = "www.easytag.de/XMLSchema_v1_0", propOrder = {

})
public class ExtensionPointsConfigurationType {

    @XmlElement(name = "ExtensionBundleSearchPath", required = true)
    protected ExtensionBundleSearchPathType extensionBundleSearchPath;
    @XmlElement(name = "ExtensionPoints", required = true)
    protected ExtensionPointsType extensionPoints;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the extensionBundleSearchPath property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionBundleSearchPathType }
     *     
     */
    public ExtensionBundleSearchPathType getExtensionBundleSearchPath() {
        return extensionBundleSearchPath;
    }

    /**
     * Sets the value of the extensionBundleSearchPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionBundleSearchPathType }
     *     
     */
    public void setExtensionBundleSearchPath(ExtensionBundleSearchPathType value) {
        this.extensionBundleSearchPath = value;
    }

    /**
     * Gets the value of the extensionPoints property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionPointsType }
     *     
     */
    public ExtensionPointsType getExtensionPoints() {
        return extensionPoints;
    }

    /**
     * Sets the value of the extensionPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionPointsType }
     *     
     */
    public void setExtensionPoints(ExtensionPointsType value) {
        this.extensionPoints = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
