//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.19 at 10:39:24 AM CEST 
//


package de.je.jmeta.extmanager.impl.jaxb.extbundles;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExtensionBundleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtensionBundleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="BundleProperties" type="{www.easytag.de/XMLSchema_v1_0}BundlePropertiesType"/>
 *         &lt;element name="BundleJar" type="{www.easytag.de/XMLSchema_v1_0}BundleJarType" minOccurs="0"/>
 *         &lt;element name="BundledExtensions" type="{www.easytag.de/XMLSchema_v1_0}BundledExtensionsType"/>
 *       &lt;/all>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtensionBundleType", namespace = "www.easytag.de/XMLSchema_v1_0", propOrder = {

})
public class ExtensionBundleType {

    @XmlElement(name = "BundleProperties", required = true)
    protected BundlePropertiesType bundleProperties;
    @XmlElement(name = "BundleJar")
    protected BundleJarType bundleJar;
    @XmlElement(name = "BundledExtensions", required = true)
    protected BundledExtensionsType bundledExtensions;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the bundleProperties property.
     * 
     * @return
     *     possible object is
     *     {@link BundlePropertiesType }
     *     
     */
    public BundlePropertiesType getBundleProperties() {
        return bundleProperties;
    }

    /**
     * Sets the value of the bundleProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link BundlePropertiesType }
     *     
     */
    public void setBundleProperties(BundlePropertiesType value) {
        this.bundleProperties = value;
    }

    /**
     * Gets the value of the bundleJar property.
     * 
     * @return
     *     possible object is
     *     {@link BundleJarType }
     *     
     */
    public BundleJarType getBundleJar() {
        return bundleJar;
    }

    /**
     * Sets the value of the bundleJar property.
     * 
     * @param value
     *     allowed object is
     *     {@link BundleJarType }
     *     
     */
    public void setBundleJar(BundleJarType value) {
        this.bundleJar = value;
    }

    /**
     * Gets the value of the bundledExtensions property.
     * 
     * @return
     *     possible object is
     *     {@link BundledExtensionsType }
     *     
     */
    public BundledExtensionsType getBundledExtensions() {
        return bundledExtensions;
    }

    /**
     * Sets the value of the bundledExtensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BundledExtensionsType }
     *     
     */
    public void setBundledExtensions(BundledExtensionsType value) {
        this.bundledExtensions = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
