(TeX-add-style-hook
 "FunctionalArchitecture"
 (lambda ()
   (LaTeX-add-labels
    "sec:FunctionalArchitectureChap"
    "sec:Grld"
    "sec:Subsystems"
    "fig:5_3_SCH_TechnicalArchitecture"
    "sec:Bootstrap"
    "sec:LibName2"
    "sec:CoreAndUserInterface"
    "sec:Techbase"
    "sec:Extensions"
    "sec:StructureofaComponentDescription"
    "sec:KompBoots"
    "sec:COMPContext"
    "sec:KompHigh"
    "sec:KompLow"
    "sec:COMPlowLevel"
    "sec:COMPdataPartManagement"
    "sec:COMPdataFormatManagement"
    "sec:COMPmediumAccess"
    "sec:KompTB"
    "sec:COMPextensionManagement"
    "sec:COMPlogging"
    "sec:COMPutility"
    "sec:COMPcomponentRegistry"
    "sec:KompExt")))

