set JAVA_HOME=H:\dev_2.0\javadev\java\jre\bin
set MACHINE_NAME="Intel(R) Core(TM)2 Duo CPU E6550@2,33GHz - 2,33GHz, 2,00 GB RAM"
set DELETE_FILES=true

:: Files
set SMALL_FILE=./data/performanceTest/files/01_SMALL.txt
set SMALL_MEDIUM_FILE=./data/performanceTest/files/02_SMALL_MEDIUM.txt
set MEDIUM_FILE=./data/performanceTest/files/03_MEDIUM.txt
set BIG_FILE=./data/performanceTest/files/04_BIG.txt
set LARGE_FILE=./data/performanceTest/files/05_LARGE.txt
set HUGE_FILE=./data/performanceTest/files/06_FUCKING_HUGE.txt

:: Block Sizes
set SMALL_BLOCK_SIZE=100
set SMALL_MEDIUM_BLOCK_SIZE=1000
set MEDIUM_BLOCK_SIZE_1=10000
set MEDIUM_BLOCK_SIZE_2=100000
set MEDIUM_BLOCK_SIZE_3=300000
set BIG_BLOCK_SIZE=1000000
set LARGE_BLOCK_SIZE=3000000
set HUGE_BLOCK_SIZE=25000000
set MEGA_BLOCK_SIZE=125000000

set CLASS_PATH=bin;../Utility/bin
set MAIN_CLASS=de.et.perf.file.FilePerformanceTest

%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %SMALL_FILE% %SMALL_BLOCK_SIZE% %SMALL_BLOCK_SIZE% %SMALL_BLOCK_SIZE% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %SMALL_MEDIUM_FILE% %SMALL_BLOCK_SIZE% %SMALL_BLOCK_SIZE% %SMALL_BLOCK_SIZE% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %MEDIUM_FILE% %SMALL_BLOCK_SIZE% %SMALL_BLOCK_SIZE% %SMALL_BLOCK_SIZE% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %BIG_FILE% %SMALL_BLOCK_SIZE% %SMALL_BLOCK_SIZE% %SMALL_BLOCK_SIZE% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %LARGE_FILE% %SMALL_BLOCK_SIZE% %SMALL_BLOCK_SIZE% %SMALL_BLOCK_SIZE% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %HUGE_FILE% %SMALL_BLOCK_SIZE% %SMALL_BLOCK_SIZE% %SMALL_BLOCK_SIZE% %DELETE_FILES%

%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %SMALL_FILE% %SMALL_MEDIUM_BLOCK_SIZE% %SMALL_MEDIUM_BLOCK_SIZE% %SMALL_MEDIUM_BLOCK_SIZE% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %SMALL_MEDIUM_FILE% %SMALL_MEDIUM_BLOCK_SIZE% %SMALL_MEDIUM_BLOCK_SIZE% %SMALL_MEDIUM_BLOCK_SIZE% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %MEDIUM_FILE% %SMALL_MEDIUM_BLOCK_SIZE% %SMALL_MEDIUM_BLOCK_SIZE% %SMALL_MEDIUM_BLOCK_SIZE% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %BIG_FILE% %SMALL_MEDIUM_BLOCK_SIZE% %SMALL_MEDIUM_BLOCK_SIZE% %SMALL_MEDIUM_BLOCK_SIZE% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %LARGE_FILE% %SMALL_MEDIUM_BLOCK_SIZE% %SMALL_MEDIUM_BLOCK_SIZE% %SMALL_MEDIUM_BLOCK_SIZE% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %HUGE_FILE% %SMALL_MEDIUM_BLOCK_SIZE% %SMALL_MEDIUM_BLOCK_SIZE% %SMALL_MEDIUM_BLOCK_SIZE% %DELETE_FILES%

%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %SMALL_FILE% %MEDIUM_BLOCK_SIZE_1% %MEDIUM_BLOCK_SIZE_1% %MEDIUM_BLOCK_SIZE_1% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %SMALL_MEDIUM_FILE% %MEDIUM_BLOCK_SIZE_1% %MEDIUM_BLOCK_SIZE_1% %MEDIUM_BLOCK_SIZE_1% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %MEDIUM_FILE% %MEDIUM_BLOCK_SIZE_1% %MEDIUM_BLOCK_SIZE_1% %MEDIUM_BLOCK_SIZE_1% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %BIG_FILE% %MEDIUM_BLOCK_SIZE_1% %MEDIUM_BLOCK_SIZE_1% %MEDIUM_BLOCK_SIZE_1% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %LARGE_FILE% %MEDIUM_BLOCK_SIZE_1% %MEDIUM_BLOCK_SIZE_1% %MEDIUM_BLOCK_SIZE_1% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %HUGE_FILE% %MEDIUM_BLOCK_SIZE_1% %MEDIUM_BLOCK_SIZE_1% %MEDIUM_BLOCK_SIZE_1% %DELETE_FILES%

%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %SMALL_FILE% %MEDIUM_BLOCK_SIZE_2% %MEDIUM_BLOCK_SIZE_2% %MEDIUM_BLOCK_SIZE_2% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %SMALL_MEDIUM_FILE% %MEDIUM_BLOCK_SIZE_2% %MEDIUM_BLOCK_SIZE_2% %MEDIUM_BLOCK_SIZE_2% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %MEDIUM_FILE% %MEDIUM_BLOCK_SIZE_2% %MEDIUM_BLOCK_SIZE_2% %MEDIUM_BLOCK_SIZE_2% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %BIG_FILE% %MEDIUM_BLOCK_SIZE_2% %MEDIUM_BLOCK_SIZE_2% %MEDIUM_BLOCK_SIZE_2% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %LARGE_FILE% %MEDIUM_BLOCK_SIZE_2% %MEDIUM_BLOCK_SIZE_2% %MEDIUM_BLOCK_SIZE_2% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %HUGE_FILE% %MEDIUM_BLOCK_SIZE_2% %MEDIUM_BLOCK_SIZE_2% %MEDIUM_BLOCK_SIZE_2% %DELETE_FILES%

%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %SMALL_FILE% %MEDIUM_BLOCK_SIZE_3% %MEDIUM_BLOCK_SIZE_3% %MEDIUM_BLOCK_SIZE_3% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %SMALL_MEDIUM_FILE% %MEDIUM_BLOCK_SIZE_3% %MEDIUM_BLOCK_SIZE_3% %MEDIUM_BLOCK_SIZE_3% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %MEDIUM_FILE% %MEDIUM_BLOCK_SIZE_3% %MEDIUM_BLOCK_SIZE_3% %MEDIUM_BLOCK_SIZE_3% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %BIG_FILE% %MEDIUM_BLOCK_SIZE_3% %MEDIUM_BLOCK_SIZE_3% %MEDIUM_BLOCK_SIZE_3% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %LARGE_FILE% %MEDIUM_BLOCK_SIZE_3% %MEDIUM_BLOCK_SIZE_3% %MEDIUM_BLOCK_SIZE_3% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %HUGE_FILE% %MEDIUM_BLOCK_SIZE_3% %MEDIUM_BLOCK_SIZE_3% %MEDIUM_BLOCK_SIZE_3% %DELETE_FILES%

%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %SMALL_MEDIUM_FILE% %BIG_BLOCK_SIZE% %BIG_BLOCK_SIZE% %BIG_BLOCK_SIZE% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %MEDIUM_FILE% %BIG_BLOCK_SIZE% %BIG_BLOCK_SIZE% %BIG_BLOCK_SIZE% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %BIG_FILE% %BIG_BLOCK_SIZE% %BIG_BLOCK_SIZE% %BIG_BLOCK_SIZE% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %LARGE_FILE% %BIG_BLOCK_SIZE% %BIG_BLOCK_SIZE% %BIG_BLOCK_SIZE% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %HUGE_FILE% %BIG_BLOCK_SIZE% %BIG_BLOCK_SIZE% %BIG_BLOCK_SIZE% %DELETE_FILES%

%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %BIG_FILE% %LARGE_BLOCK_SIZE% %LARGE_BLOCK_SIZE% %LARGE_BLOCK_SIZE% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %LARGE_FILE% %LARGE_BLOCK_SIZE% %LARGE_BLOCK_SIZE% %LARGE_BLOCK_SIZE% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %HUGE_FILE% %LARGE_BLOCK_SIZE% %LARGE_BLOCK_SIZE% %LARGE_BLOCK_SIZE% %DELETE_FILES%

%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %LARGE_FILE% %HUGE_BLOCK_SIZE% %HUGE_BLOCK_SIZE% %HUGE_BLOCK_SIZE% %DELETE_FILES%
%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %HUGE_FILE% %HUGE_BLOCK_SIZE% %HUGE_BLOCK_SIZE% %HUGE_BLOCK_SIZE% %DELETE_FILES%

%JAVA_HOME%/java -cp %CLASS_PATH% %MAIN_CLASS% %MACHINE_NAME% %HUGE_FILE% %MEGA_BLOCK_SIZE% %MEGA_BLOCK_SIZE% %MEGA_BLOCK_SIZE% %DELETE_FILES%